language: generic
dist: bionic

install:
  # Newer tools
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  # spell
  - apt-cache search spell
  - sudo apt install aspell
  # proselint
  - sudo pip install proselint
  # pandoc
  - sudo apt install pandoc 
  # imagemagick
  - sudo apt install imagemagick
  # PDF creation
  - sudo apt install texlive-latex-recommended texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended texlive-extra-utils texlive-humanities texlive-full texlive-games texlive-pictures texlive-science texlive-xetex ktikz
  # R
  - sudo apt install r-base-core r-cran-readr r-cran-stringr r-cran-testthat
  - Rscript -e 'remotes::install_github("ropensci/beautier")'

script:
  - make
  # proselint
  - proselint $(find | grep .*\.md) | egrep -v "curly_quotes" || true
  # Build article
  - rm -f pirouette_article.pdf
  - make
  - if [ ! -f pirouette_article.pdf ]; then echo "file 'pirouette_article.pdf' not found" ; exit 1 ; fi
  # Count words, must be below 3000 for 'Applications'
  - make count_words


