#!/bin/bash
#
# The pirouette_article repo does not run the examples itself.
# To be able to use the actual figures, the results
# of the run examples are copied to the pirouette_article folder
#
# Usage:
#  
#   ./copy_figures_and_tables_to_here

# Copy errors.png
for i in $(seq 1 12);
do
  echo $i
  from="../pirouette_example_"$i"/example_"$i"/errors.png"
  echo $from
  to="example_"$i"/errors.png"
  echo $to
  cp $from $to
done