#!/bin/bash
#
# Copies the results from the pirouette examples to here.
#
# Usage:
#
#   ./scripts/copy_figs_from_pir_example_to_here
#
#

# Go to folder above pirouette_article root folder
cd ..

# Copy the pirouette_examples' results to the pirouette_article root folder
for index in 1 2 3
do
  source_folder=$(echo "/home/richel/GitHubs/pirouette_example_"$index)
  echo $source_folder
  source_subfolder=$(echo $source_folder"/example_"$index"_314")
  echo $source_subfolder
  target_folder=$(echo "/home/richel/GitHubs/pirouette_article/example_"$index)
  echo $target_folder
  cp $source_subfolder/*.png $target_folder
  cp $source_subfolder/*.latex $target_folder
done
