#!/bin/bash
# Script to run all:
#   * Installation
#   * Creating all figures
# This script can be run as-is, as it will 
# sbatch the needed jobs itself
#
# Usage:
#
# ./run
#
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=1G
#SBATCH --job-name=run
#SBATCH --output=run.log
# Install first
jobid=$(sbatch install | cut -d ' ' -f 4)

# After install, create all figures
sbatch --dependency=afterok:$jobid run_r_script example_1.R
sbatch --dependency=afterok:$jobid run_r_script example_2.R
sbatch --dependency=afterok:$jobid run_r_script example_3.R
sbatch --dependency=afterok:$jobid run_r_script example_4.R
sbatch --dependency=afterok:$jobid run_r_script example_5.R

