#!/bin/bash
# Script to run all examples locally
# 
# Usage:
#
# ./run_examples
#

cd ~/GitHubs/pirouette_example_1; time Rscript example_1.R
cd ~/GitHubs/pirouette_example_2; time Rscript example_2.R
cd ~/GitHubs/pirouette_example_3; time Rscript example_3.R
