#!/bin/bash
# Script to investigate Issue #41
# This script can be run as-is, as it will 
# sbatch the needed jobs itself
#
# Usage:
#
# ./run_41_parallel
#
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=100M
#SBATCH --job-name=run_41_parallel
#SBATCH --output=run_41_parallel_%j.log

for rng_seed in $(seq 1 100)
do
  echo "rng_seed: "$rng_seed
  sbatch run_r_script example_3.R $rng_seed
done

