#!/bin/bash
# Script to investigate Issue #41
# This script can be run as-is, as it will 
# sbatch the needed jobs itself
#
# Usage:
#
# ./run_41
#
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=100M
#SBATCH --job-name=run_41
#SBATCH --output=run_41_%j.log

rng_seed=1
echo "rng_seed: "$rng_seed
job_id=$(sbatch run_r_script example_3.R $rng_seed | cut -d ' ' -f 4)
echo "job_id: "$job_id

for rng_seed in $(seq 2 3)
do
  echo "rng_seed: "$rng_seed
  job_id=$(sbatch --dependency=afterany:$job_id run_r_script example_3.R $rng_seed | cut -d ' ' -f 4)
  echo "job_id: "$job_id
done

